sudo: false

language: c

env:
  - STACK_YAML=stack.yaml

addons:
  apt:
    packages:
      - libgmp-dev

install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version
  - stack setup --no-terminal

script:
  - stack test --no-terminal --ghc-options="-Werror"

cache:
  directories:
    - $HOME/.stack
