name: repl-server
version: "0.1"

dependencies:
  - base
  - base-compat
  - process
  - getopt-generics
  - unix
  - http-types
  - directory
  - bytestring
  - network
  - wai
  - warp
  - http-client
  - string-conversions

ghc-options:
  - -threaded
  - -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - silently
      - mockery
      - async

executables:
  repl-server:
    main: repl-server.hs
    source-dirs:
      - src
  repl-client:
    main: repl-client.hs
    source-dirs:
      - src
