name: repl-server
version: "0.1"

dependencies:
  - base
  - process
  - getopt-generics
  - unix
  - http-types
  - network
  - wai
  - warp

ghc-options:
  - -threaded

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - silently
      - mockery

executables:
  repl-server:
    main: repl-server.hs
    source-dirs:
      - src
