name: repl-server
version: "0.1"

dependencies:
  - base
  - base-compat
  - process
  - getopt-generics
  - unix
  - http-types
  - directory
  - bytestring
  - network
  - wai
  - warp
  - http-client
  - string-conversions
  - servant
  - transformers

ghc-options:
  - -threaded
  - -Wall
  - -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - silently
      - mockery
      - async
      - servant-server
      - servant-client

executables:
  repl-server:
    main: repl-server.hs
    source-dirs:
      - src
    dependencies:
      - servant-server
  repl-client:
    main: repl-client.hs
    source-dirs:
      - src
    dependencies:
      - servant-client
